# US County Demographics

In this project, we will be analyzing demographics data on US counties betwen 2010-2019 using a __[dataset obtained from Kaggle](https://www.kaggle.com/datasets/mexwell/us-country-demographics)__. The primary focus of this project is to utilize advanced SQL queries, pandas, and Tableau dashboarding to explore and visualize information regarding US counties. The table below provides information on each of the columns found in the dataset:

| Original Column Name | Renamed Column Name | Data Type | Description | 
|:---------------:|:-----------------:|:-----------------|:-----------|
| County | County | String | County name | 
| State | State | String | State name | 
| Age.Percent 65 and Older | Age 65+ | Float | Estimated percentage of population whose ages are equal or greater than 65 years old are produced for the United States states and counties as well as for the Commonwealth of Puerto Rico and its municipios (county-equivalents for Puerto Rico). | 
| Age.Percent Under 18 Years | Age Under 18 | Float | Estimated percentage of population whose ages are under 18 years old are produced for the United States states and counties as well as for the Commonwealth of Puerto Rico and its municipios (county-equivalents for Puerto Rico). | 
| Age.Percent Under 5 Years	| Age Under 5 | Float | Estimated percentage of population whose ages are under 5 years old are produced for the United States states and counties as well as for the Commonwealth of Puerto Rico and its municipios (county-equivalents for Puerto Rico). | 
| Education.Bachelor's Degree or Higher	| Education Bachelor's+ | Float	| Percentage for the people who attended college but did not receive a degree and people who received an associate's bachelor's master's or professional or doctorate degree. These data include only persons 25 years old and over. The percentages are obtained by dividing the counts of graduates by the total number of persons 25 years old and over. Tha data is collected from 2015 to 2019. | 
| Education.High School or Higher | Education High School+ | Float | Percentage of people whose highest degree was a high school diploma or its equivalent people who attended college but did not receive a degree and people who received an associate's bachelor's master's or professional or doctorate degree. These data include only persons 25 years old and over. The percentages are obtained by dividing the counts of graduates by the total number of persons 25 years old and over. Tha data is collected from 2015 to 2019 | 
| Employment.Nonemployer Establishments | Nonemployer Establishments | Integer | An establishment is a single physical location at which business is conducted or where services or industrial operations are performed. It is not necessarily identical with a company or enterprise which may consist of one establishment or more. The data was collected from 2018. | 
| Ethnicities.American Indian and Alaska Native Alone | American Indian and Alaska Native | Float | Estimated percentage of population having origins in any of the original peoples of North and South America (including Central America) and who maintains tribal affiliation or community attachment. This category includes people who indicate their race as "American Indian or Alaska Native" or report entries such as Navajo Blackfeet Inupiat Yup'ik or Central American Indian groups or South American Indian groups. |
| Ethnicities.Asian Alone | Asian | Float | Estimated percentage of population having origins in any of the original peoples of the Far East Southeast Asia or the Indian subcontinent including for example Cambodia China India Japan Korea Malaysia Pakistan the Philippine Islands Thailand and Vietnam. This includes people who reported detailed Asian responses such as: "Asian Indian " "Chinese " "Filipino " "Korean " "Japanese " "Vietnamese " and "Other Asian" or provide other detailed Asian responses. |
| Ethnicities.Black Alone | Black | Float | Estimated percentage of population having origins in any of the Black racial groups of Africa. It includes people who indicate their race as "Black or African American " or report entries such as African American Kenyan Nigerian or Haitian. |
| Ethnicities.Hispanic or Latino | Hispanic or Latino | Float | Estimated percentage of population of Cuban Mexican Puerto Rican South or Central American or other Spanish culture or origin regardless of race. This includes people who reported detailed Hispanic or Latino groups. |
| Ethnicities.Native Hawaiian and Other Pacific Islander Alone | Native Hawaiian or Pacific Islander | Float | Estimated percentage of population having origins in any of the Black racial groups of Africa. It includes people who indicate their race as "Black or African American " or report entries such as African American Kenyan Nigerian or Haitian. | 
| Ethnicities.Two or More Races | 2+ Races | Float | Estimated percentage of population choosing to provide two or more races either by checking two or more race response check boxes by providing multiple responses or by some combination of check boxes and other responses. For data product purposes "Two or More Races" refers to combinations of two or more of the following race categories: "White " "Black or African American " American Indian or Alaska Native " "Asian " Native Hawaiian or Other Pacific Islander " or "Some Other Race". | 
| Ethnicities.White Alone | White | Float | Estimated percentage of population having origins in any of the original peoples of Europe the Middle East or North Africa. It includes people who indicate their race as "White" or report entries such as Irish German Italian Lebanese Arab Moroccan or Caucasian. |
| Ethnicities.White Alone not Hispanic or Latino | White not Hispanic or Latino | Float | Estimated percentage of population having origins in any of the original peoples of Europe the Middle East or North Africa. It includes people who indicate their race as "White" or report entries such as Irish German Italian Lebanese Arab Moroccan or Caucasian. | 
| Housing.Homeownership Rate | Homeownership Rate | Float | A housing unit is owner-occupied if the owner or co-owner lives in the unit even if it is mortgaged or not fully paid for. The owner or co-owner must live in the unit and usually is Person 1 on the questionnaire. This homeownership rate is computed by dividing the number of owner-occupied housing units by the number of occupied housing units or households from 2015 to 2019. | 
| Housing.Households | Households | Integer | Number of households including all the persons who occupy a housing unit as their usual place of residence from 2015 to 2019. | 
| Housing.Housing Units | Housing Units | Integer |	Estimated number of housing units apartments mobile homes groups of rooms or single rooms that are occupied (or if vacant is intended for occupancy) as separate living quarters beginning with July 1 2019. | 
| Housing.Median Value of Owner-Occupied Units | Median Value of Owner-Occupied Units | Integer | Median value of housing units which are owner-occupied if the owner or co-owner lives in the unit even if it is mortgaged or not fully paid for from 2015 to 2019. Median value calculations are rounded to the nearest hundred dollars. | 
| Housing.Persons per Household | Persons per Household | Float | Percentage for the number of people per household or average household size from 2015 to 2019. | 
| Income.Median Houseold Income | Median Household Income | Integer |	Median of income in the Past 12 Months collected from 2015 to 2019 - Income of Households: This includes the income of the householder and all other individuals 15 years old and over in the household whether they are related to the householder or not. Because many households consist of only one person average household income is usually less than average family income. | 
| Income.Per Capita Income | Per Capita Income | Integer | Per capita income is the mean income computed for every man woman and child in a particular group including those living in group quarters. It is derived by dividing the aggregate income of a particular group by the total population in that group. This measure is rounded to the nearest whole dollar. For the complete definition go to ACS subject definitions "Income in the Past 12 Months Per Capita Income." The data is collected from 2015 to 2019. | 
| Miscellaneous.Foreign Born | Foreign Born | Float | Estimated percentage of population who was not a U.S. citizen or a U.S. national at birth. This includes respondents who indicated they were a U.S. citizen by naturalization or not a U.S. citizen. from 2015 to 2019. | 
| Miscellaneous.Land Area | Land Area | Float | Land area measurements are originally recorded as whole square meters (to convert square meters to square kilometers divide by 1 000 000; to convert square kilometers to square miles divide by 2.58999; to convert square meters to square miles divide by 2 589 988) in 2010. |
| Miscellaneous.Language Other than English at Home | Language Other than English | Float | Percentage for the number of people who knew languages other than English but did not use them at home who only used them elsewhere or whose usage was limited to a few expressions or slang were excluded from 2015 to 2019. Tabulations of language spoken at home include only the responses of persons 5 years old and over. |
| Miscellaneous.Living in Same House +1 Years | Living in Same House 1+ Years | Float | Percentage for the residence in conjunction with location of current residence to determine the extent of residential mobility of the population and the resulting redistribution of the population across the various states metropolitan areas and regions of the country from 2015 to 2019. | 
| Miscellaneous.Manufacturers Shipments | Manufacturers Shipments | Integer |	The manufacturing sector comprises establishments engaged in the mechanical physical or chemical transformation of materials substances or components into new products. The 2012 Economic Census classifies businesses according to the North American Industry Classification System (NAICS) 2012. | 
| Miscellaneous.Mean Travel Time to Work | Mean Travel Time to Work | Float | Travel time to work refers to the total number of minutes that it usually took the person to get from home to work each day during the reference week. The elapsed time includes time spent waiting for public transportation picking up passengers in carpools and time spent in other activities related to getting to work. Mean travel time to work is obtained by dividing the total number of minutes by the number of workers 16 years old and over who did not work at home. Mean travel time to work is rounded to the nearest tenth of a minute. The data was collected from 2015 to 2019. | 
| Miscellaneous.Percent Female | Percent Female | Float | Estimated percentage of female population who are produced for the United States states and counties as well as for the Commonwealth of Puerto Rico and its municipios (county-equivalents for Puerto Rico). | 
| Miscellaneous.Veterans | Veterans | Integer | Population of men and women who have served (even for a short time) but are not currently serving on active duty in the U.S. Army Navy Air Force Marine Corps or the Coast Guard or who served in the U.S. Merchant Marine during World War II from 2015 to 2019. |
| Population.2020 Population | 2020 Population | Integer | The population of people in a specified geographic area on April 1 2020. |
| Population.2010 Population | 2010 Population | Integer | The population of people in a specified geographic area on April 1 2010. |
| Population.Population per Square Mile | Population per Square Mile | Float | Population and housing unit density computed by dividing the total population or number of housing units within a geographic entity by the land area of that entity measured in square miles or in square kilometers in 2010. |
| Sales.Accommodation and Food Services Sales | Accommodation and Food Services Sales | Integer | The Accommodation and Food Services Sales sector comprises establishments providing customers with lodging and/or prepared meals snacks and beverages for immediate consumption. The 2012 Economic Census classifies businesses according to the North American Industry Classification System (NAICS) 2012. Sales includes payments from customers for services rendered from the use of facilities and from merchandise sold. If tax-exempt sales includes dues and assessments from members and affiliates. |
| Sales.Retail Sales | Retail Sales | Integer | The retail trade sector comprises establishments engaged in retailing merchandise generally without transformation and rendering services incidental to the sale of merchandise. The 2007 Economic Census classifies businesses according to the North American Industry Classification System (NAICS) 2012. Sales include merchandise sold for cash or credit at retail and wholesale by establishments primarily engaged in retail trade. | 
| Employment.Firms.Total | Total Firms | Integer | All nonfarm businesses filing Internal Revenue Service tax forms as individual proprietorships partnerships or any type of corporation and with receipts of $1 000 or more. The data was collected in 2012. | 
| Employment.Firms.Women-Owned | Women-Owned Firms | Integer | All women-owned nonfarm businesses filing Internal Revenue Service tax forms as individual proprietorships partnerships or any type of corporation and with receipts of $1 000 or more. The data was collected in 2012. |
| Employment.Firms.Men-Owned | Men-Owned Firms | Integer | All men-owned nonfarm businesses filing Internal Revenue Service tax forms as individual proprietorships partnerships or any type of corporation and with receipts of $1 000 or more. The data was collected in 2012. |
| Employment.Firms.Minority-Owned | Minority-Owned Firms | Integer	| All nonfarm businesses owned by equally minority filing Internal Revenue Service tax forms as individual proprietorships partnerships or any type of corporation and with receipts of $1 000 or more. The data was collected in 2012. |
| Employment.Firms.Nonminority-Owned | Nonminority-Owned Firms | Integer | All nonfarm businesses owned by equally nonminority filing Internal Revenue Service tax forms as individual proprietorships partnerships or any type of corporation and with receipts of $1 000 or more. The data was collected in 2012. | 
| Employment.Firms.Veteran-Owned | Veteran-Owned Firms | Integer | All nonfarm businesses owned by veteran filing Internal Revenue Service tax forms as individual proprietorships partnerships or any type of corporation and with receipts of $1 000 or more. The data was collected in 2012. | 
| Employment.Firms.Nonveteran-Owned | Nonveteran-Owned Firms | Integer | All nonfarm businesses owned by non-veteran filing Internal Revenue Service tax forms as individual proprietorships partnerships or any type of corporation and with receipts of $1 000 or more. The data was collected in 2012. |

## Exploratory Data Analysis
Before beginning any analysis, we will perform some exploratory data analysis to explore trends and relationships amongst different variables of interest in our dataset.

In [1]:
# Imports
!pip install -q pandas
!pip install -q numpy
!pip install --upgrade pip
!pip install -q sqlalchemy==1.4.46
!pip install pandas --q pandasql 


import pandas as pd
import numpy as np
from sqlalchemy import text, sql
from pandasql import sqldf

Requirement already satisfied: pip in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (24.0)

In [2]:
county_demo_df = pd.read_csv('county_demographics.csv')
county_demo_df.head()

,County,State,Age.Percent 65 and Older,Age.Percent Under 18 Years,Age.Percent Under 5 Years,Education.Bachelor's Degree or Higher,Education.High School or Higher,Employment.Nonemployer Establishments,Ethnicities.American Indian and Alaska Native Alone,Ethnicities.Asian Alone,...,Population.Population per Square Mile,Sales.Accommodation and Food Services Sales,Sales.Retail Sales,Employment.Firms.Total,Employment.Firms.Women-Owned,Employment.Firms.Men-Owned,Employment.Firms.Minority-Owned,Employment.Firms.Nonminority-Owned,Employment.Firms.Veteran-Owned,Employment.Firms.Nonveteran-Owned
0,Abbeville County,SC,22.4,19.8,4.7,15.6,81.7,1416,0.3,0.4,...,51.8,12507,91371,1450,543,689,317,1080,187,1211
1,Acadia Parish,LA,15.8,25.8,6.9,13.3,79.0,4533,0.4,0.3,...,94.3,52706,602739,4664,1516,2629,705,3734,388,4007
2,Accomack County,VA,24.6,20.7,5.6,19.5,81.5,2387,0.7,0.8,...,73.8,53568,348195,2997,802,1716,335,2560,212,2536
3,Ada County,ID,14.9,23.2,5.6,38.5,95.2,41464,0.8,2.7,...,372.8,763099,5766679,41789,14661,19409,3099,36701,3803,35132
4,Adair County,IA,23.0,21.8,5.6,18.5,94.2,609,0.3,0.5,...,13.5,-1,63002,914,304,499,0,861,185,679

For the purposes of using SQL, I will be renaming several of the column names to make querying simpler. The table in the beginning shows the original and renamed column names.

In [3]:
county_demo_df.columns
county_demo_df = county_demo_df.rename(columns = {
    'Age.Percent 65 and Older': 'Age 65+', 
    'Age.Percent Under 18 Years': 'Age Under 18',
    'Age.Percent Under 5 Years': 'Age Under 5', 
    "Education.Bachelor's Degree or Higher": "Education Bachelor's+",
    "Education.High School or Higher": "Education High School+", 
    'Employment.Nonemployer Establishments': 'Nonemployer Establishments',
    'Ethnicities.American Indian and Alaska Native Alone': 'American Indian and Alaska Native', 
    'Ethnicities.Asian Alone': 'Asian', 
    'Ethnicities.Black Alone': 'Black', 
    'Ethnicities.Hispanic or Latino': 'Hispanic or Latino', 
    'Ethnicities.Native Hawaiian and Other Pacific Islander Alone': 'Native Hawaiian or Pacific Islander', 
    'Ethnicities.Two or More Races': '2+ Races', 
    'Ethnicities.White Alone': 'White', 
    'Ethnicities.White Alone\t not Hispanic or Latino': 'White not Hispanic or Latino',
    'Housing.Homeownership Rate': 'Homeownership Rate', 
    'Housing.Households': 'Households', 
    'Housing.Housing Units': 'Housing Units', 
    'Housing.Median Value of Owner-Occupied Units': 'Median Value of Owner-Occupied Units', 
    'Housing.Persons per Household': 'Persons per Household', 
    'Income.Median Houseold Income': 'Median Household Income', 
    'Income.Per Capita Income': 'Per Capita Income', 
    'Miscellaneous.Foreign Born': 'Foreign Born', 
    'Miscellaneous.Land Area': 'Land Area',
    'Miscellaneous.Language Other than English at Home': 'Language Other than English', 
    'Miscellaneous.Living in Same House +1 Years': 'Living in Same House 1+ Years', 
    'Miscellaneous.Manufacturers Shipments': 'Manufacturers Shipments', 
    'Miscellaneous.Mean Travel Time to Work': 'Mean Travel Time to Work', 
    'Miscellaneous.Percent Female': 'Percent Female', 
    'Miscellaneous.Veterans': 'Veterans',
    'Population.2020 Population': '2020 Population',
    'Population.2010 Population': '2010 Population', 
    'Population.Population per Square Mile': 'Population per Square Mile',
    'Sales.Accommodation and Food Services Sales': 'Accomodation and Food Services Sales', 
    'Sales.Retail Sales': 'Retail Sales', 
    'Employment.Firms.Total': 'Total Firms', 
    'Employment.Firms.Women-Owned': 'Women-Owned Firms', 
    'Employment.Firms.Men-Owned': 'Men-Owned Firms', 
    'Employment.Firms.Minority-Owned': 'Minority-Owned Firms', 
    'Employment.Firms.Nonminority-Owned': 'Nonminority-Owned Firms', 
    'Employment.Firms.Veteran-Owned': 'Veteran-Owned Firms', 
    'Employment.Firms.Nonveteran-Owned': 'Nonveteran-Owned Firms'
})

In [9]:
county_demo_df.columns
county_demo_df[['Age 65+']]

      Age 65+
0        22.4
1        15.8
2        24.6
3        14.9
4        23.0
...       ...
3134     19.3
3135     18.7
3136     13.2
3137     14.6
3138      9.6

[3139 rows x 1 columns]

In [13]:
query = '''SELECT "Age 65+" from county_demo_df'''
sqldf(query, env = None)

      Age 65+
0        22.4
1        15.8
2        24.6
3        14.9
4        23.0
...       ...
3134     19.3
3135     18.7
3136     13.2
3137     14.6
3138      9.6

[3139 rows x 1 columns]